### ISSUE TITLE
Key Viewer Text size and box width

### ISSUE THREAD

**Issue by Davidtank70** [PizzaLovers007/AdofaiTweaks#1]
I love the mod but I do have one small issue that seems like it could be easily fixed.
There is an issue that is especially noticeable when using a second mod to add permanence to the keystrokes tracked on the key viewer as once nearing around the 20,000 presses mark the size of the text causes the number to be split across two lines because it cant fit the entire number on one line anymore as it is too long to fit in the box. I see a couple solutions for this. 1) You could add a setting for font size to change the font size of the number of presses 2) you could add a setting for the size of the box to make the boxes longer [there's already a setting for size but that just makes everything larger box and number] 3) you could make it so that it automatically adjusts the font size so it always fits in one line. I think option 1 would be easiest to implement personally. 
Thanks for the awesome mod I hope you consider this improvement as I would really like to see it implemented and for the issue with it jumping between two lines to be fixed.

**Comment by Davidtank70** [comment]
![image](https://user-images.githubusercontent.com/36216761/141534255-bbb754d1-4ea4-4ad8-9c48-7dea0631a98f.png)
Here's an example of what I mean.

**Comment by PizzaLovers007** [comment]
Sorry for the really long delay! I've fixed this in a425d4fdf7d557f186ef99fe9cf6680eb1ffd85e, which should be in the next release.
