### ISSUE TITLE
[Bug] Custom death message on Restrict Judgement doesn't work

### ISSUE THREAD

**Issue by balt-dev** [PizzaLovers007/AdofaiTweaks#11]
https://user-images.githubusercontent.com/59123926/173931148-5c25798f-af40-476d-aa2d-b35c176cb1aa.mp4

**Comment by CrackThrough** [comment]
Oh yeah, the text there changes instantly so it's nearly invisible. @NoBrain0917 is currently investigating!

**Comment by PizzaLovers007** [comment]
Closing this out now that it's been fixed
