### ISSUE TITLE
Volume slider does not work

### ISSUE THREAD

**Issue by PizzaLovers007** [PizzaLovers007/AdofaiTweaks#13]

**Comment by CrackThrough** [comment]
Oh,,, This is something that I worked on for a while before, but this might be incompatible for now.
I'm going to remove this redundant feature if @PizzaLovers007 agrees.

**Comment by CrackThrough** [comment]
Hi! This is an irrelevant option now so I will remove this. Sorry for the long delay, but I'll try to implement this option in the main game instead. 😅
