### ISSUE TITLE
Custom Asset Bundles guide image broken

### ISSUE THREAD

**Issue by sjkim04** [PizzaLovers007/AdofaiTweaks#2]
I noticed that the [/Wiki/Custom Unity Assets Bundles for ADOFAI.md](https://github.com/PizzaLovers007/AdofaiTweaks/blob/1eed0774501456d5b5a5b62d32c4350a35aa3e92/Wiki/Custom%20Unity%20Asset%20Bundles%20for%20ADOFAI.md), which was made in ba16ba74cde037efd3b04b62a4db34ee08dd91e1, seems that the image was linked directly from @PizzaLovers007’s C:\ drive.
I hope he can upload the original image and fix the links.

**Comment by PizzaLovers007** [comment]
Thanks for letting me know! I've fixed it and added it to the wiki page here: https://github.com/PizzaLovers007/AdofaiTweaks/wiki/Custom-Unity-Asset-Bundles-for-ADOFAI
