### ISSUE TITLE
[Feature Request] Multi-tap tiles in the editor.

### ISSUE THREAD

**Issue by nxfx21** [PizzaLovers007/AdofaiTweaks#20]
Currently, **the only way** to make **2 button tiles** is to use **pseudos** which most people **don't like.** Having the multi-tap tiles will **make it possible** to chart other Rhythm Journey songs, as well as **new possibilities** for the **ADOFAI Mapping community**, so, if possible can you **please** add Multi-tap tiles in the editor?

**Comment by PizzaLovers007** [comment]
I think this is out of scope for what this mod should provide, which are simple tweaks to the game that can be toggleable. Maybe a different mod can add this.

**Comment by nxfx21** [comment]
Nice to hear from you, but i don't know how to mod ADOFAI. Thanks for
considering this.
