### ISSUE TITLE
Does not save keystrokes

### ISSUE THREAD

**Issue by MaRi0ooo** [PizzaLovers007/AdofaiTweaks#22]
After a long game in ADOFAI, the next time you start the count of clicks is reset.

**Comment by PizzaLovers007** [comment]
I decided on keeping the key viewer very simple, so a lot of features that other key viewers have aren't added. There's another key viewer mod that has a lot more features, so you can use that one instead.

From the ADOFAI.gg discord:
https://cdn.discordapp.com/attachments/886661471533162526/1062418162831867914/KeyViewer.zip
(v3.6.1)

There are several other mods as well, here's the invite link: https://discord.gg/adofaigg

**Comment by MaRi0ooo** [comment]
Thanks for the info and links. ^_^
