### ISSUE TITLE
Kill Player on Restricted Judgement no longer allows Level to Restart when pressing any key

### ISSUE THREAD

**Issue by phaicm** [PizzaLovers007/AdofaiTweaks#25]
With the latest release 2.6.3 of Adofai Tweaks on latest live version of ADOFAI (2.5.0), 

using Restrict Judgements by setting the restriction to instantly kill the player, you will be stuck on the death screen. 

Pressing any key will not automatically restart the level (or go back to checkpoint) as normal.

This forces the player to now press ESC->Restart to restart the level

**Comment by PizzaLovers007** [comment]
This should be fixed in the latest release! https://github.com/PizzaLovers007/AdofaiTweaks/releases/tag/v2.6.4
