### ISSUE TITLE
[Bug] Settings not working, not accepting key input

### ISSUE THREAD

**Issue by Musikid-Official** [PizzaLovers007/AdofaiTweaks#28]
ADoFaI Version: 2.6.1
ADOFAI Tweaks Versions: 2.6.1, 2.6.5

ADoFaI is not registering my key inputs. Before I updated ADoFaI from 2.6.0 to 2.6.1 (as I assume that's the cause of the problem) I had a key restriction set to A, S, D, F, J, K, L, and Semicolon. Now, key inputs don't register at all. Same with mouse clicks. Log was too big to fit. Status is still Active, Options doesn't work. Disabling the mod fixes the problem.

**Comment by Acrith** [comment]
Having exactly the same problem.
ADOFAI Tweaks tested 2.6.1, 2.6.3, 2.6.5

This started to happen after latest update. Interesting this, only Key Limiter crashes entire mod setting.
XML file shows like this - the bit with "ActiveKeys"/"ActiveAsyncKeys" is simply empty. 
Deleting the file **KeyLimiterSettings.xml** will restore access to settings and clicks will be registered. Ticking "Key Limiter" will break entire mod again.

```
<?xml version="1.0" encoding="utf-8"?>
<KeyLimiterSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <IsEnabled>true</IsEnabled>
  <IsExpanded>true</IsExpanded>
  <ActiveKeys />
  <ActiveAsyncKeys />
  <ShowKeyViewer>false</ShowKeyViewer>
  <ViewerOnlyGameplay>false</ViewerOnlyGameplay>
  <AnimateKeys>true</AnimateKeys>
  <KeyViewerSize>100</KeyViewerSize>
  <KeyViewerXPos>0.89</KeyViewerXPos>
  <KeyViewerYPos>0.03</KeyViewerYPos>
  <LimitKeyOnCLS>true</LimitKeyOnCLS>
  <LimitKeyOnMainScreen>true</LimitKeyOnMainScreen>
  <PressedOutlineColor>
    <r>0</r>
    <g>0</g>
    <b>0</b>
    <a>1</a>
  </PressedOutlineColor>
  <ReleasedOutlineColor>
    <r>0</r>
    <g>0</g>
    <b>0</b>
    <a>1</a>
  </ReleasedOutlineColor>
  <PressedBackgroundColor>
    <r>0</r>
    <g>0</g>
    <b>0</b>
    <a>1</a>
  </PressedBackgroundColor>
  <ReleasedBackgroundColor>
    <r>0</r>
    <g>0</g>
    <b>0</b>
    <a>1</a>
  </ReleasedBackgroundColor>
  <PressedTextColor>
    <r>0</r>
    <g>0</g>
    <b>0</b>
    <a>1</a>
  </PressedTextColor>
  <ReleasedTextColor>
    <r>0</r>
    <g>0</g>
    <b>0</b>
    <a>1</a>
  </ReleasedTextColor>
</KeyLimiterSettings>
```

**Comment by PizzaLovers007** [comment]
Thanks for reporting! I'm not on my usual setup, so I won't be able to fix this for a while unfortunately (maybe a week or so). In the meantime, please disable KeyLimiter using Acrith's instructions.

**Comment by PizzaLovers007** [comment]
This should now be fixed with https://github.com/PizzaLovers007/AdofaiTweaks/releases/tag/v2.6.6.
