### ISSUE TITLE
Option screen was hidden but can't be opened

### ISSUE THREAD

**Issue by siki666** [PizzaLovers007/AdofaiTweaks#32]
### When adjusting some Settings in the game, the full option screen is hidden and cannot be clicked and opened.✖
Maybe mod manager's fault.I don't know.🤔
Now I can only uninstall the mod,install the mod again and restart the game(but sometimes can't be any help).😶

**Comment by PizzaLovers007** [comment]
This should be fixed with the latest release! https://github.com/PizzaLovers007/AdofaiTweaks/releases/tag/v2.6.8
