### ISSUE TITLE
adofai 

### ISSUE THREAD

**Issue by SmileLiu2233** [PizzaLovers007/AdofaiTweaks#4]

**Comment by SmileLiu2233** [comment]
nice mod! but adofai v1.15.5(r85) ban your mods, please repair!

**Comment by PizzaLovers007** [comment]
I don't seem to have any issues with it, can you post your logs? It should be in the Ctrl+F10 menu > Logs > Open detailed log

**Comment by SmileLiu2233** [comment]
Thank you for your reply
my game log


Mono path[0] = 'E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/Managed'
Mono config path = 'E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/MonoBleedingEdge/etc'
Initialize engine version: 2021.2.8f1 (d0e5f0a7b06a)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
&nbsp; &nbsp; Version:&nbsp; Direct3D 11.0 [level 11.0]
&nbsp; &nbsp; Renderer: NVIDIA GeForce GT 620 (ID=0xf01)
&nbsp; &nbsp; Vendor:&nbsp; &nbsp;NVIDIA
&nbsp; &nbsp; VRAM:&nbsp; &nbsp; &nbsp;969 MB
&nbsp; &nbsp; Driver:&nbsp; &nbsp;23.21.13.9135
Begin MonoManager ReloadAssembly




[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.22.15.0.
[Manager] OS: Microsoft Windows NT 10.0.18363.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2021.2.81.
[Manager] Game: A Dance of Fire and Ice.
[Manager] Mods path: E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods.
Fallback handler could not load library E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/MonoBleedingEdge/data-000001ED36475060.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/MonoBleedingEdge/data-000001ED36180050.dll
[Manager] Injection successful.
- Completed reload, in&nbsp; 1.002 seconds
<RI&gt; Initializing input.


<RI&gt; Input initialized.


<RI&gt; Initialized touch support.


UnloadTime: 1.311200 ms
[Manager] Parsing mods.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\AccuracyLimiter\Info.json'.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\AdofaiTweaks\Info.json'.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\KeyViewer\Info.json'.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\MusicTimestamp\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[AccuracyLimiter] Version '2.0.0'. Loading.
[AccuracyLimiter] [Error] Error loading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\AccuracyLimiter\AccuracyLimiter.dll'.
[AccuracyLimiter] [Exception] ReflectionTypeLoadException - Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
&nbsp; at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
&nbsp; at System.Reflection.Assembly.GetTypes () [0x00000] in <47ab72e0328040438980f9c23608e1ec&gt;:0&nbsp;
&nbsp; at UnityModManagerNet.UnityModManager+ModEntry.Load () [0x004b6] in <34910f3e8aa64912a55c26c5696bd4da&gt;:0&nbsp;
System.IO.FileNotFoundException: Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[AccuracyLimiter] Loading time 0.04 s.
[AdofaiTweaks] Version '2.3.6'. Loading.
[AdofaiTweaks] [Error] Error trying to call 'AdofaiTweaks.Startup.Load'.
[AdofaiTweaks] [Exception] TargetInvocationException - Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
&nbsp; at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
&nbsp; at System.Reflection.Assembly.GetTypes () [0x00000] in <47ab72e0328040438980f9c23608e1ec&gt;:0&nbsp;
&nbsp; at AdofaiTweaks.AdofaiTweaks+<&gt;c.<Setup&gt;b__16_0 (System.Reflection.Assembly a) [0x00000] in <bc8b6b8c65774f9f9a79498bf2c5e03f&gt;:0&nbsp;
&nbsp; at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00051] in <4392bd4b1cc44e5fa38e8fbdbabf7b07&gt;:0&nbsp;
&nbsp; at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].ToArray () [0x00033] in <4392bd4b1cc44e5fa38e8fbdbabf7b07&gt;:0&nbsp;
&nbsp; at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x0000a] in <4392bd4b1cc44e5fa38e8fbdbabf7b07&gt;:0&nbsp;
&nbsp; at System.Linq.OrderedEnumerable`1[TElement].ToArray () [0x00000] in <4392bd4b1cc44e5fa38e8fbdbabf7b07&gt;:0&nbsp;
&nbsp; at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x0000a] in <4392bd4b1cc44e5fa38e8fbdbabf7b07&gt;:0&nbsp;
&nbsp; at System.Linq.OrderedEnumerable`1[TElement].ToList () [0x00000] in <4392bd4b1cc44e5fa38e8fbdbabf7b07&gt;:0&nbsp;
&nbsp; at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <4392bd4b1cc44e5fa38e8fbdbabf7b07&gt;:0&nbsp;
&nbsp; at AdofaiTweaks.AdofaiTweaks.Setup (UnityModManagerNet.UnityModManager+ModEntry modEntry) [0x0009a] in <bc8b6b8c65774f9f9a79498bf2c5e03f&gt;:0&nbsp;
&nbsp; at AdofaiTweaks.Startup.Load (UnityModManagerNet.UnityModManager+ModEntry modEntry) [0x00000] in <bc8b6b8c65774f9f9a79498bf2c5e03f&gt;:0&nbsp;
&nbsp; at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&amp;)
&nbsp; at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <47ab72e0328040438980f9c23608e1ec&gt;:0&nbsp;
&nbsp; &nbsp;--- End of inner exception stack trace ---
&nbsp; at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <47ab72e0328040438980f9c23608e1ec&gt;:0&nbsp;
&nbsp; at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <47ab72e0328040438980f9c23608e1ec&gt;:0&nbsp;
&nbsp; at UnityModManagerNet.UnityModManager+ModEntry.Invoke (System.String namespaceClassnameMethodname, System.Object&amp; result, System.Object[] param, System.Type[] types) [0x00011] in <34910f3e8aa64912a55c26c5696bd4da&gt;:0&nbsp;
[AdofaiTweaks] Not loaded.
[AdofaiTweaks] Loading time 0.23 s.
[KeyViewer] To skip (disabled).
[MusicTimestamp] Version '0.0.10'. Loading.
[MusicTimestamp] Active.
[MusicTimestamp] Loading time 0.10 s.
[Manager] FINISH. SUCCESSFUL LOADED 2/4 MODS.




[Manager] Spawning.
Version r85, (2022/04/01 3:45 PM)
Saving backup.
Saving backup.
Discord was not initialized: Discord.ResultException: InternalError
&nbsp; at Discord.Discord..ctor (System.Int64 clientId, System.UInt64 flags) [0x00327] in <c202f9119ff8478898d2c39bb12a60ed&gt;:0&nbsp;
&nbsp; at DiscordController.OnEnable () [0x0001f] in <bbef96145de84501be795406b050f559&gt;:0&nbsp;
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
[Manager] Checking updates.
[Manager] No network connection or firewall blocked.
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 3.856900 ms
[Manager] Cancel start. Already started.
[Manager] Cancel start. Already started.
[Manager] Cancel start. Already started.
[Manager] Cancel start. Already started.
Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 23705.
Total: 8.642200 ms (FindLiveObjects: 1.620100 ms CreateObjectMapping: 0.618000 ms MarkObjects: 6.295000 ms&nbsp; DeleteObjects: 0.108700 ms)


Unloading 2 Unused Serialized files (Serialized files now loaded: 0)
Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 23705.
Total: 8.880600 ms (FindLiveObjects: 2.115900 ms CreateObjectMapping: 0.454700 ms MarkObjects: 6.233900 ms&nbsp; DeleteObjects: 0.075400 ms)


Shader warmup: 78 shaders 260 combinations 0.013s
<color=#0099bc&gt;<b&gt;DOTWEEN ► </b&gt;</color&gt;Max Tweens reached: capacity has automatically been increased from 500/50 to 1250/50. Use DOTween.SetTweensCapacity to set it manually at startup





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PizzaLovers007/AdofaiTweaks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午2:00
***@***.***&gt;;
抄送:&nbsp;"what' ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PizzaLovers007/AdofaiTweaks] adofai  (Issue #4)





 
I don't seem to have any issues with it, can you post your logs? It should be in the Ctrl+F10 menu &gt; Logs &gt; Open detailed log

**Comment by PizzaLovers007** [comment]
It looks like you're on version 2.3.6, try updating to the latest version (found here: https://github.com/PizzaLovers007/AdofaiTweaks/releases/tag/v2.4.2)

**Comment by SmileLiu2233** [comment]
is mod 2.4.2 version log:
Mono path[0] = 'E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/Managed'
Mono config path = 'E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/MonoBleedingEdge/etc'
Initialize engine version: 2021.2.8f1 (d0e5f0a7b06a)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
&nbsp; &nbsp; Version:&nbsp; Direct3D 11.0 [level 11.0]
&nbsp; &nbsp; Renderer: NVIDIA GeForce GT 620 (ID=0xf01)
&nbsp; &nbsp; Vendor:&nbsp; &nbsp;NVIDIA
&nbsp; &nbsp; VRAM:&nbsp; &nbsp; &nbsp;969 MB
&nbsp; &nbsp; Driver:&nbsp; &nbsp;23.21.13.9135
Begin MonoManager ReloadAssembly




[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.22.15.0.
[Manager] OS: Microsoft Windows NT 10.0.18363.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2021.2.81.
[Manager] Game: A Dance of Fire and Ice.
[Manager] Mods path: E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods.
Fallback handler could not load library E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/MonoBleedingEdge/data-0000023F2C657090.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/A Dance of Fire and Ice_new/A Dance of Fire and Ice_Data/MonoBleedingEdge/data-0000023F2C58A040.dll
[Manager] Injection successful.
- Completed reload, in&nbsp; 0.658 seconds
<RI&gt; Initializing input.


<RI&gt; Input initialized.


<RI&gt; Initialized touch support.


UnloadTime: 1.286700 ms
[Manager] Parsing mods.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\AccuracyLimiter\Info.json'.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\AdofaiTweaks-master\Info.json'.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\KeyViewer\Info.json'.
[Manager] Reading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\MusicTimestamp\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[AccuracyLimiter] Version '2.0.0'. Loading.
[AccuracyLimiter] [Error] Error loading file 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\AccuracyLimiter\AccuracyLimiter.dll'.
[AccuracyLimiter] [Exception] ReflectionTypeLoadException - Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
&nbsp; at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
&nbsp; at System.Reflection.Assembly.GetTypes () [0x00000] in <47ab72e0328040438980f9c23608e1ec&gt;:0&nbsp;
&nbsp; at UnityModManagerNet.UnityModManager+ModEntry.Load () [0x004b6] in <34910f3e8aa64912a55c26c5696bd4da&gt;:0&nbsp;
System.IO.FileNotFoundException: Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ModUle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[AccuracyLimiter] Loading time 0.02 s.
[AdofaiTweaks] Version '2.4.2'. Loading.
[AdofaiTweaks] [Error] File 'E:\SteamLibrary\steamapps\A Dance of Fire and Ice_new\Mods\AdofaiTweaks-master\AdofaiTweaks.dll' not found.
[AdofaiTweaks] Loading time 0.00 s.
[KeyViewer] Version '2.2.0'. Loading.
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
&nbsp; at KeyViewer.KeyViewer.UpdateKeys () [0x0002a] in <6dc67f33c658412d886f2e4622bf3c93&gt;:0&nbsp;
&nbsp; at KeyViewer.KeyViewer.Awake () [0x0003b] in <6dc67f33c658412d886f2e4622bf3c93&gt;:0&nbsp;
UnityEngine.GameObject:Internal_AddComponentWithType(GameObject, Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
KeyViewer.KeyViewerTweak:OnEnable()
KeyViewer.Main:OnToggle(ModEntry, Boolean)
UnityModManagerNet.ModEntry:set_Active(Boolean)
UnityModManagerNet.ModEntry:Load()
UnityModManagerNet.ModEntry:set_Active(Boolean)
UnityModManagerNet.UnityModManager:_Start()
UnityModManagerNet.UnityModManager:Start()
UnityModManagerNet.Injector:Prefix_Start()
ADOStartup:ADOStartup.Startup_Patch2()
ADOBase:Startup()
scnSplash:Awake()


[KeyViewer] Active.
[KeyViewer] Loading time 0.90 s.
[MusicTimestamp] Version '0.0.10'. Loading.
[MusicTimestamp] Active.
[MusicTimestamp] Loading time 0.07 s.
[Manager] FINISH. SUCCESSFUL LOADED 2/4 MODS.




[Manager] Spawning.
Version r85, (2022/04/01 3:45 PM)
Saving backup.
Saving backup.
Discord was not initialized: Discord.ResultException: InternalError
&nbsp; at Discord.Discord..ctor (System.Int64 clientId, System.UInt64 flags) [0x00327] in <c202f9119ff8478898d2c39bb12a60ed&gt;:0&nbsp;
&nbsp; at DiscordController.OnEnable () [0x0001f] in <bbef96145de84501be795406b050f559&gt;:0&nbsp;
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
[Manager] Checking updates.
[Manager] No network connection or firewall blocked.
Unloading 6 Unused Serialized files (Serialized files now loaded: 1)
UnloadTime: 2.348000 ms
[Manager] Cancel start. Already started.
[Manager] Cancel start. Already started.
[Manager] Cancel start. Already started.
[Manager] Cancel start. Already started.
Unloading 13 unused Assets to reduce memory usage. Loaded Objects now: 23954.
Total: 8.765200 ms (FindLiveObjects: 1.990100 ms CreateObjectMapping: 0.572100 ms MarkObjects: 6.102200 ms&nbsp; DeleteObjects: 0.100300 ms)


Unloading 1 Unused Serialized files (Serialized files now loaded: 1)
Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 23954.
Total: 7.734400 ms (FindLiveObjects: 1.637300 ms CreateObjectMapping: 0.453500 ms MarkObjects: 5.601300 ms&nbsp; DeleteObjects: 0.041800 ms)


Shader warmup: 78 shaders 260 combinations 0.015s
<color=#0099bc&gt;<b&gt;DOTWEEN ► </b&gt;</color&gt;Max Tweens reached: capacity has automatically been increased from 500/50 to 1250/50. Use DOTween.SetTweensCapacity to set it manually at startup







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PizzaLovers007/AdofaiTweaks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 中午11:00
***@***.***&gt;;
抄送:&nbsp;"what' ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PizzaLovers007/AdofaiTweaks] adofai  (Issue #4)





 
It looks like you're on version 2.3.6, try updating to the latest version (found here: https://github.com/PizzaLovers007/AdofaiTweaks/releases/tag/v2.4.2)

**Comment by PizzaLovers007** [comment]
I think you downloaded the source code, not the mod. Download "AdofaiTweaks-2.4.2.zip" from the link that I sent.

**Comment by SmileLiu2233** [comment]
thank，&nbsp;succeed




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PizzaLovers007/AdofaiTweaks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 中午11:00
***@***.***&gt;;
抄送:&nbsp;"what' ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PizzaLovers007/AdofaiTweaks] adofai  (Issue #4)





 
It looks like you're on version 2.3.6, try updating to the latest version (found here: https://github.com/PizzaLovers007/AdofaiTweaks/releases/tag/v2.4.2)
