### ISSUE TITLE
Hide dotted radius ring 

### ISSUE THREAD

**Issue by balt-dev** [PizzaLovers007/AdofaiTweaks#7]
You know the dotted ring with the planets? Yeah I'd like a setting to remove that.

**Comment by CrackThrough** [comment]
specifically white? do you have any errors in the log file?

**Comment by balt-dev** [comment]
No, this is more a feature request. I'd more be asking to have a setting to toggle or turn down the opacity of the dotted circle with the planets:
![image](https://user-images.githubusercontent.com/59123926/172521496-0d0ee0cb-24cf-4c39-b35a-b23e202c34ed.png)
(I'd make a pull request but I don't know C# sorry)

**Comment by CrackThrough** [comment]
ooh but this _could_ harm the readability of planet radius changing, have you thought about any way to not make planet radius change unreadable?

**Comment by PizzaLovers007** [comment]
The latest update has the option to hide the ring by turning the opacity to 0%!

It definitely does harm the readability, but I think that's up to the player at that point since that's the option that they decided to use.
